<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('.:: Software4you ::.')) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/ckeditor.js'))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/img-3.png') ?>" alt="logo Software4you"/>&nbsp;</a>
                </div>
                
                <div class="collapse navbar-collapse">
                
                    <ul class="nav navbar-nav">
                        <li class="hover"><a href="<?php echo $this->url('clientes') ?>"><?php echo $this->translate('Clientes') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="hover"><a href="<?php echo $this->url('servicos') ?>"><?php echo $this->translate('Servicios') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="hover"><a href="<?php echo $this->url('produtos') ?>"><?php echo $this->translate('Productos') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="hover"><a href="<?php echo $this->url('sobrenos') ?>"><?php echo $this->translate('Sobre Nosotros') ?></a></li>
                    </ul>                    
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="hover"><a href="<?php echo $this->url('carreira') ?>"><?php echo $this->translate('Trabaja con Nosotros') ?></a></li>
                    </ul>                    
                    <ul class="nav navbar-nav">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </ul>
                    <ul class="nav navbar-nav">
		      <li class="hover">
                        <select name="lang"  class="active">
                          <option value="es-ES" selected >Es</value>
			  <option value="pt-BR" >Pt</value>
			  <option value="fr-FR">Fr</value>
			  <option value="en-US">En</value>
                        </select>
                      </li>
                    </ul>                                        
                </div>                                
           
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
	      <ul class="nav navbar-nav">
		<li class="hover">
		  <a href="<?php echo $this->url('clientes') ?>"><?php echo $this->translate('Clientes') ?></a>
		</li>
	      </ul>                                      
	      <ul class="nav navbar-nav">
		  &nbsp;
	      </ul>                    
	      <ul class="nav navbar-nav">
		<li class="hover">
		  <a href="<?php echo $this->url('servicos') ?>"><?php echo $this->translate('Serviços') ?></a>
		</li>
	      </ul>
	      <ul class="nav navbar-nav">
		  &nbsp;
	      </ul>                    
	      <ul class="nav navbar-nav">
		<li class="hover">
		  <a href="<?php echo $this->url('produtos') ?>"><?php echo $this->translate('Produtos') ?></a>
		</li>
	      </ul>
	      <ul class="nav navbar-nav">
		  &nbsp;
	      </ul>                    
	      <ul class="nav navbar-nav">
		<li class="hover">
		  <a href="<?php echo $this->url('sobrenos') ?>"><?php echo $this->translate('Sobre Nós') ?></a>
		</li>
	      </ul>
	      <ul class="nav navbar-nav">
		  &nbsp;
	      </ul>                    
	      <ul class="nav navbar-nav">
		<li class="hover">
		  <a href="<?php echo $this->url('carreira') ?>"><?php echo $this->translate('Carreiras') ?></a>
		</li>
	      </ul>                                          
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
