<div class="jumbotron">
<form>
<h3><b>Admin site</b></h3>
<br/>
<a href="http://127.0.0.1:8080/admin/home">home</a>
<br/>
<a href="http://127.0.0.1:8080/admin/clientes">clientes</a>
<br/>
<a href="http://127.0.0.1:8080/admin/servicos">servicos</a>
<br/>
<a href="http://127.0.0.1:8080/admin/produtos">produtos</a>
<br/>
<a href="http://127.0.0.1:8080/admin/sobre-nos">sobre-nos</a>
<br/>
<a href="http://127.0.0.1:8080/admin/carreira">carreira</a>
</div>


