<div class="jumbotron">
    <img src="<?php echo $this->basePath('img/img-2.png') ?>" alt="banner"/>
    <img src="<?php echo $this->basePath('img/img-4.png') ?>" alt="serviços"/>
<?php foreach ($user as $use) : ?>
 <tr>
     <td>
         id=> <?php echo $use->id;?>
         email=> <?php echo $use->email;?>
         senha=> <?php echo $use->password;?>
     </td>
 </tr>
 <?php endforeach; ?>    
</div>


